version: '3.8'

services:
  app:
    image: openjdk:17
    container_name: spring_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: ["sh", "-c", "./gradlew bootRun"]